export enum ECities {
  Lviv = 'Lviv',
  Kyiv = 'Kiev',
  Rivne = 'Rivne',
  Ternopil = 'Ternopil',
  Kharkiv = 'Kharkiv',
  Kherson = 'Kherson',
  Yalta = 'Yalta',
  Alupka = 'Alupka',
  Mexico = 'Mexico',
  London = 'London',
  Vancouver = 'Vancouver',
  Warshava = 'Varshava',
  Lissabon = 'Lissabon',
  Bern = 'Bern',
  Praga = 'Praga',
  Paris = 'Paris',
  Berlin = 'Berlin',
  Toronto = 'Toronto',
  Sidney = 'Sidney',
  Rio = 'Rio',
  Washington = 'Washington',
  Tokio = 'Tokio',
  Pekin = 'Pekin',
  Porto = 'Port'
}
